<?php
require_once __DIR__ . '/../includes/auth.php';
$admin = require_admin(); $pdo = db();
$view = $_GET['view'] ?? 'dashboard';
if (!in_array($view, ['dashboard','users','reports','sessions','activity'], true)) $view='dashboard';
function admin_log(PDO $pdo,int $adminId,string $action,string $type,?int $id,string $details):void { $pdo->prepare('INSERT INTO admin_actions (admin_id,action,target_type,target_id,details) VALUES (?,?,?,?,?)')->execute([$adminId,$action,$type,$id,$details]); }
if ($_SERVER['REQUEST_METHOD']==='POST') {
 verify_csrf(); $action=$_POST['action']??''; $id=(int)($_POST['id']??0);
 if ($action==='user_status' && $id!==(int)$admin['id']) { $status=($_POST['status']??'')==='suspended'?'suspended':'active'; $pdo->prepare("UPDATE users SET status=? WHERE id=? AND role<>'admin'")->execute([$status,$id]); admin_log($pdo,(int)$admin['id'],'Changed user status','user',$id,'Status changed to '.$status.'.'); set_flash('success','User status updated.'); }
 elseif ($action==='delete_user' && $id!==(int)$admin['id']) { $s=$pdo->prepare("SELECT first_name,last_name FROM users WHERE id=? AND role<>'admin'");$s->execute([$id]);$target=$s->fetch();if($target){$pdo->prepare('DELETE FROM users WHERE id=?')->execute([$id]);admin_log($pdo,(int)$admin['id'],'Deleted user','user',$id,'Deleted '.full_name($target).'.');set_flash('success','User and related data were deleted.');} }
 elseif ($action==='report_update') { $status=$_POST['status']??'reviewing';if(!in_array($status,['open','reviewing','resolved','dismissed'],true))$status='reviewing';$pdo->prepare('UPDATE reports SET status=?,admin_notes=?,handled_by=? WHERE id=?')->execute([$status,trim($_POST['admin_notes']??''),(int)$admin['id'],$id]);admin_log($pdo,(int)$admin['id'],'Updated report','report',$id,'Report marked '.$status.'.');set_flash('success','Report updated.'); }
 elseif ($action==='delete_session') { $pdo->prepare('DELETE FROM study_sessions WHERE id=?')->execute([$id]);admin_log($pdo,(int)$admin['id'],'Deleted session','session',$id,'Removed a study session.');set_flash('success','Session deleted.'); }
 redirect('index.php?view='.urlencode($_POST['return_view']??$view));
}
$q=trim($_GET['q']??'');
$stats=['users'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='user'")->fetchColumn(),'sessions'=>(int)$pdo->query('SELECT COUNT(*) FROM study_sessions')->fetchColumn(),'open_reports'=>(int)$pdo->query("SELECT COUNT(*) FROM reports WHERE status IN ('open','reviewing')")->fetchColumn(),'suspended'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE status='suspended'")->fetchColumn()];
$users=$reports=$sessions=$activity=[];
if($view==='users'){$s=$pdo->prepare("SELECT u.*,COUNT(DISTINCT ss.id) hosted_sessions,COUNT(DISTINCT p.session_id) joined_sessions FROM users u LEFT JOIN study_sessions ss ON ss.host_id=u.id LEFT JOIN session_participants p ON p.user_id=u.id WHERE u.first_name LIKE ? OR u.last_name LIKE ? OR u.email LIKE ? OR u.school LIKE ? GROUP BY u.id ORDER BY u.created_at DESC");$like='%'.$q.'%';$s->execute([$like,$like,$like,$like]);$users=$s->fetchAll();}
elseif($view==='reports'||$view==='dashboard'){$reports=$pdo->query("SELECT r.*,CONCAT(a.first_name,' ',a.last_name) reporter_name,CONCAT(t.first_name,' ',t.last_name) reported_name,ss.title session_title FROM reports r JOIN users a ON a.id=r.reporter_id LEFT JOIN users t ON t.id=r.reported_user_id LEFT JOIN study_sessions ss ON ss.id=r.session_id ORDER BY FIELD(r.status,'open','reviewing','resolved','dismissed'),r.created_at DESC".($view==='dashboard'?' LIMIT 5':''))->fetchAll();}
elseif($view==='sessions'){$s=$pdo->prepare("SELECT ss.*,CONCAT(u.first_name,' ',u.last_name) host_name,COUNT(p.user_id) participant_count FROM study_sessions ss JOIN users u ON u.id=ss.host_id LEFT JOIN session_participants p ON p.session_id=ss.id WHERE ss.title LIKE ? OR ss.subject LIKE ? OR u.first_name LIKE ? GROUP BY ss.id ORDER BY ss.session_date DESC");$like='%'.$q.'%';$s->execute([$like,$like,$like]);$sessions=$s->fetchAll();}
elseif($view==='activity'){$activity=$pdo->query("SELECT a.*,CONCAT(u.first_name,' ',u.last_name) admin_name FROM admin_actions a LEFT JOIN users u ON u.id=a.admin_id ORDER BY a.created_at DESC LIMIT 100")->fetchAll();}
$titles=['dashboard'=>'Overview','users'=>'User Management','reports'=>'Reports Center','sessions'=>'Session Management','activity'=>'Admin Activity'];
function anav(string $n,string $v):string{return 'sb-link '.($n===$v?'active':'');} function badge(string $s):string{return match($s){'active','resolved'=>'background:#EFFFD1;color:#679000','suspended','open'=>'background:#FFEAE6;color:var(--coral)','reviewing'=>'background:#EAF7FF;color:#1680B8',default=>'background:#F0EEF5;color:var(--muted)'};}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($titles[$view])?> - StudyBuddy Admin</title><script src="https://cdn.tailwindcss.com"></script><link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@500&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/style.css"></head><body><div class="flex min-h-screen">
<aside class="sb-nav w-[240px] shrink-0 min-h-screen flex flex-col justify-between py-6 px-4 sticky top-0 h-screen"><div><a href="index.php" class="flex items-center gap-2 px-2 mb-8"><span class="w-8 h-8 rounded-lg flex items-center justify-center font-bold" style="background:var(--lime)">A</span><span><b class="block font-display text-white">StudyBuddy</b><small class="block uppercase tracking-[.18em] text-[#B7B5C2]">Admin console</small></span></a><nav class="flex flex-col gap-1"><?php foreach([['dashboard','Overview'],['users','Users'],['reports','Reports'],['sessions','Sessions'],['activity','Activity Log']] as[$k,$l]):?><a href="index.php?view=<?=$k?>" class="<?=anav($k,$view)?>"><span>●</span><?=$l?><?php if($k==='reports'&&$stats['open_reports']):?><span class="ml-auto pill !px-2" style="background:var(--coral);color:white"><?=$stats['open_reports']?></span><?php endif?></a><?php endforeach?></nav></div><div><a href="../home.php" class="sb-link">← Back to app</a><a href="../logout.php" class="sb-link">Log out</a></div></aside>
<main class="flex-1 min-w-0 px-5 md:px-8 py-8 max-w-[1400px]"><header class="flex items-center justify-between mb-8"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-[var(--violet)]">Administration</p><h1 class="font-display text-[28px] font-bold"><?=e($titles[$view])?></h1><p class="text-sm text-[var(--muted)]">Manage the StudyBuddy community and keep it safe.</p></div><div class="flex items-center gap-3"><?=avatar_html($admin)?><div class="hidden sm:block"><p class="text-sm font-semibold"><?=e(full_name($admin))?></p><p class="text-xs text-[var(--muted)]">Administrator</p></div></div></header><?php render_flashes()?>
<?php if($view==='dashboard'):?><div class="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mb-7"><?php foreach([['users','Total users','var(--violet)'],['sessions','Study sessions','var(--sky)'],['open_reports','Needs attention','var(--coral)'],['suspended','Suspended','var(--lime-deep)']] as[$k,$l,$c]):?><div class="card p-5"><div class="w-9 h-2 rounded-full mb-5" style="background:<?=$c?>"></div><p class="font-mono-data text-3xl font-bold"><?=$stats[$k]?></p><p class="text-sm text-[var(--muted)]"><?=$l?></p></div><?php endforeach?></div><div class="card overflow-hidden"><div class="p-5 flex justify-between"><div><h2 class="font-display text-lg font-bold">Priority reports</h2><p class="text-xs text-[var(--muted)]">Issues that need a decision.</p></div><a href="?view=reports" class="btn-ghost text-xs">View all</a></div><?php if(!$reports):?><p class="border-t p-8 text-center text-sm text-[var(--muted)]">No reports yet. Everything looks clear.</p><?php endif?><?php foreach($reports as$r):?><a href="?view=reports#report-<?=$r['id']?>" class="flex items-center gap-4 border-t border-[var(--line)] p-4"><span class="w-2 h-2 rounded-full bg-[var(--coral)]"></span><span class="flex-1"><b class="block text-sm"><?=e($r['category'])?></b><small class="text-[var(--muted)]">Reported by <?=e($r['reporter_name'])?></small></span><span class="pill" style="<?=badge($r['status'])?>"><?=e(ucfirst($r['status']))?></span></a><?php endforeach?></div>
<?php elseif($view==='users'):?><form class="card p-3 mb-5 flex gap-2"><input type="hidden" name="view" value="users"><input class="flex-1 bg-transparent px-3 outline-none text-sm" name="q" value="<?=e($q)?>" placeholder="Search name, email, or school"><button class="btn-dark text-sm !py-2">Search</button></form><div class="card overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-[#F1EEE5] text-xs uppercase"><tr><th class="p-4">User</th><th class="p-4">School / course</th><th class="p-4">Activity</th><th class="p-4">Status</th><th class="p-4 text-right">Actions</th></tr></thead><tbody><?php foreach($users as$u):?><tr class="border-t"><td class="p-4"><div class="flex gap-3 items-center"><?=avatar_html($u)?><div><b><?=e(full_name($u))?></b><?php if($u['role']==='admin'):?> <small class="text-[var(--violet)]">ADMIN</small><?php endif?><p class="text-xs text-[var(--muted)]"><?=e($u['email'])?></p></div></div></td><td class="p-4"><?=e($u['school'])?><p class="text-xs text-[var(--muted)]"><?=e($u['course_strand'])?></p></td><td class="p-4 font-mono-data text-xs"><?=(int)$u['hosted_sessions']?> hosted · <?=(int)$u['joined_sessions']?> joined</td><td class="p-4"><span class="pill" style="<?=badge($u['status'])?>"><?=e(ucfirst($u['status']))?></span></td><td class="p-4"><div class="flex justify-end gap-2"><?php if($u['role']!=='admin'):?><form method="POST"><?=csrf_field()?><input type="hidden" name="action" value="user_status"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="hidden" name="return_view" value="users"><input type="hidden" name="status" value="<?=$u['status']==='active'?'suspended':'active'?>"><button class="btn-ghost text-xs !py-2"><?=$u['status']==='active'?'Suspend':'Restore'?></button></form><form method="POST" onsubmit="return confirm('Permanently delete this user and related sessions?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_user"><input type="hidden" name="id" value="<?=$u['id']?>"><input type="hidden" name="return_view" value="users"><button class="btn-ghost text-xs !py-2 text-[var(--coral)]">Delete</button></form><?php endif?></div></td></tr><?php endforeach?></tbody></table></div>
<?php elseif($view==='reports'):?><div class="space-y-4"><?php if(!$reports):?><div class="card p-10 text-center text-[var(--muted)]">No reports submitted.</div><?php endif?><?php foreach($reports as$r):?><article id="report-<?=$r['id']?>" class="card p-5"><div class="flex justify-between gap-3"><div><span class="pill" style="<?=badge($r['status'])?>"><?=e(ucfirst($r['status']))?></span><h2 class="font-display text-lg font-bold mt-2"><?=e($r['category'])?></h2><p class="text-xs text-[var(--muted)]">From <?=e($r['reporter_name'])?> · <?=e(date('M j, Y g:i A',strtotime($r['created_at'])))?></p></div><p class="text-sm text-right">User: <b><?=e($r['reported_name']?:'None')?></b><br>Session: <b><?=e($r['session_title']?:'None')?></b></p></div><p class="mt-4 p-4 rounded-xl bg-[var(--paper)] text-sm"><?=nl2br(e($r['details']))?></p><form method="POST" class="grid md:grid-cols-[180px_1fr_auto] gap-3 mt-4 items-end"><?=csrf_field()?><input type="hidden" name="action" value="report_update"><input type="hidden" name="id" value="<?=$r['id']?>"><input type="hidden" name="return_view" value="reports"><div class="field"><label>Status</label><select name="status"><?php foreach(['open','reviewing','resolved','dismissed']as$s):?><option value="<?=$s?>" <?=selected_attr($r['status'],$s)?>><?=ucfirst($s)?></option><?php endforeach?></select></div><div class="field"><label>Admin notes</label><input name="admin_notes" value="<?=e($r['admin_notes'])?>" placeholder="Action taken"></div><button class="btn-dark">Save update</button></form></article><?php endforeach?></div>
<?php elseif($view==='sessions'):?><form class="card p-3 mb-5 flex gap-2"><input type="hidden" name="view" value="sessions"><input class="flex-1 bg-transparent px-3 outline-none text-sm" name="q" value="<?=e($q)?>" placeholder="Search sessions, subjects, or hosts"><button class="btn-dark text-sm !py-2">Search</button></form><div class="grid lg:grid-cols-2 gap-4"><?php foreach($sessions as$s):?><div class="session-card p-5"><div class="tab tab-<?=e(session_tab($s['subject']))?>"></div><small class="text-[var(--muted)]"><?=e($s['subject'])?></small><h2 class="font-display font-bold text-lg"><?=e($s['title'])?></h2><p class="text-sm text-[var(--muted)]">By <?=e($s['host_name'])?> · <?=e($s['location'])?></p><div class="flex justify-between items-center mt-5 pt-4 border-t"><span class="font-mono-data text-xs"><?=(int)$s['participant_count']?>/<?=(int)$s['capacity']?> joined</span><form method="POST" onsubmit="return confirm('Delete this session?')"><?=csrf_field()?><input type="hidden" name="action" value="delete_session"><input type="hidden" name="id" value="<?=$s['id']?>"><input type="hidden" name="return_view" value="sessions"><button class="btn-ghost text-xs !py-2 text-[var(--coral)]">Delete</button></form></div></div><?php endforeach?></div>
<?php else:?><div class="card overflow-hidden"><?php foreach($activity as$a):?><div class="p-4 border-b flex gap-4"><span class="w-9 h-9 rounded-full flex items-center justify-center bg-[#EFFFD1]">✓</span><div><p class="text-sm"><b><?=e($a['admin_name']?:'Former admin')?></b> · <?=e($a['action'])?></p><p class="text-xs text-[var(--muted)]"><?=e($a['details'])?> · <?=e(date('M j, Y g:i A',strtotime($a['created_at'])))?></p></div></div><?php endforeach?><?php if(!$activity):?><p class="p-10 text-center text-[var(--muted)]">No admin activity yet.</p><?php endif?></div><?php endif?></main></div></body></html>
